language: php
php:
  - 5.3
  - 5.6
addons:
  firefox: 'latest'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
  global:
  - FIREFOX_NIGHTLY_BIN=firefox
  - CHROME_BIN=google-chrome-stable
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.4.1 WP_MULTISITE=0
matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
before_script:
  - ./bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - make test
  - make test-sw
